server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_route
          uri: lb://CLOUD-PAYMENT-SERVICE
          #          uri: http://localhost:8001
          predicates:
            - Path=/payment/get/**
        - id: payment_route2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
            - After=2021-01-30T15:02:00.329+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy
            - Header=X-Request-id, \d+
            - Method=GET
eureka:
  instance:
    #hostname: localhost #eureka服务端实例名称
    hostname: cloud-gateway
  client:
    register-with-eureka: true #不向注册中心注册自己
    fetch-registry: true #表示自己就是注册中心,不需要检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
