server:
  port: 8001


spring:
  application:
    name: cloud-provider-hystrix-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka
#  instance:
#    instance-id: payment8001
#    prefer-ip-address: true
#    #eureka客户端向服务端发送心跳的时间间隔,30秒
#    lease-renewal-interval-in-seconds: 2
#    #eureka服务端在收到最后一次心跳后等待时间上限,90秒
#    lease-expiration-duration-in-seconds: 5